@startuml
|Użytkownik|
start
:Kliknięcie w przycisk logowania;
|#AntiqueWhite|System|
:Wywołanie strony logowania Google;
|Google|
:Załadowanie formularza 
do logowania;
|Użytkownik|
:Logowanie na konto Google;
|System|
:Wywołanie weryfikacji Google IDToken;
|Google|
:Weryfikacja Google IDToken;
if (sukces?) then (tak)
    |System|
    if (użytkownik istnieje \nw systemie?) then (tak)
    else (nie)
        |System|
        :Zapis danych
        nowego użytkownika;
    endif
else (nie)
    |System|
    :Wyświetlenie komunikatu
    o niepowodzeniu weryfikacji;
    stop
endif
|System|
:Przejście do listy wpisów Wiki;
stop
@enduml