@startuml
|Użytkownik|
start
:Nawigacja do listy ofert pracy;
|#AntiqueWhite|System|
:Załadowanie danych o liście aktualnych ofert pracy;
|#AntiqueWhite|System|
:Wyświetlenie aktualnych ofert pracy;
stop
@enduml