@startuml
|Użytkownik|
start
:Kliknięcie przycisku dodania wpisu Wiki;
|#AntiqueWhite|System|
:Sprawdzenie uprawnienia użytkownika
FN PRV CREATE INFORMATION;
if (posiada uprawnienie?) then (tak)
    |System|
    :Nawigacja do formularza 
    nowego wpisu Wiki;
    :Załadowanie listy firm 
    dostępnych do wyboru;
    |Użytkownik|
    :Wypełnienie i zatwierdzenie formularza;
    |System|
    :Zapis nowego wpisu Wiki;
    :Nawigacja do poprzedniej strony;
else (nie)
    |System|
    :Wyświetlenie komunikatu
    o braku uprawnień;
endif
stop
@enduml