@startuml
|Użytkownik|
start
:Kliknięcie przycisku dodania RA
w widoku szczegółów oferty pracy;
|#AntiqueWhite|System|
:Sprawdzenie uprawnienia użytkownika
FN PRV CREATE REFERRAL;
if (posiada uprawnienie?) then (tak)
    |System|
    :Nawigacja do formularza
    nowego RA;
    |Użytkownik|
    :Wypełnienie i zatwierdzenie formularza;
    |System|
    if (istnieje już aktywne RA \nprzypisane dodanej oferty pracy \nstworzone przez użytkownika?) then (tak)
        |System|
        :Wyświetlenie komunikatu
        z informacją o niepowodzeniu;
    
    else (nie)
        |System|
        :Zapis nowego RA;
        :Nawigacja do strony z listą RA;
    endif
else (nie)
    |System|
    :Wyświetlenie komunikatu
    o braku uprawnień;
endif
stop
@enduml