@startuml
|Użytkownik|
start
:Kliknięcie jednej z opcji głosowania na elemencie listy wpisów Wiki;
|#AntiqueWhite|System|
:Zapis głosu użytkownika;
|#AntiqueWhite|System|
:Wyświetlenie zaktualizowanej listy wpisów Wiki;
stop
@enduml