@startuml

hide empty members

class User {
    userId : String
    username : String
    email : String
    imageUrl : String
    provider : String
}

enum Privilege {
    FN_PRV_CREATE_INFORMATION
    FN_PRV_CREATE_REFERRAL
}

class Company {
    companyId : String
    companyName : String
    address : String
    language : String
}

enum RecruitmentType {
    INTERVIEW
    TEST
}

class Information {
    informationId : int
    content : String
}

enum Vote {
    UP
    DOWN
}

class InformationVote {
}

class JobAnnouncement {
    jobId : int
    city : String
    jobTitle : String
    jobDescription : String
    minSalary : int
    maxSalary : int 
    closingDate : Date
}

enum ProgrammingLanguage {
    JAVA
    JAVASCRIPT
    PYTHON
    ...
}

class ReferralAnnouncement {
    referralId : int
    referralDescription : String 
    referralBonus : int 
    referralBonusPercentage : double
}

User "privileges" *---> Privilege

InformationVote -> Vote : < value
Information -> RecruitmentType : < recruitmentType
JobAnnouncement "languages" *---> ProgrammingLanguage
Information "language" ---> ProgrammingLanguage

Information "author *" --> "1" User 
Information "company *" --> "1" Company

InformationVote "voter" --* "authorVotes" User 
InformationVote "informationId" --* "informationVotes" Information

JobAnnouncement "company" --* "jobAnnouncements" Company 

ReferralAnnouncement "author *" --> "1" User
ReferralAnnouncement "job *" --> "1" JobAnnouncement


@enduml