@startuml
left to right direction

actor user

  usecase UC_7 as "**UC_7** 
  // Job // 
  Wyświetl listę ofert pracy"
  usecase UC_8 as "**UC_8** 
  // Job // 
  Wyświetl szczegóły oferty pracy"

  usecase UC_9 as "**UC_9** 
  // Referral // 
  Dodaj RA"
  usecase UC_10 as "**UC_10** 
  // Referral // 
  Wyświetl listę RA"
  usecase UC_11 as "**UC_11** 
  // Referral // 
  Wyświetl szczegóły RA"

    user --> UC_7
    user --> UC_10

    UC_8 ..> UC_7 : extends
    UC_9 ..> UC_8 : extends
    UC_9 ..> UC_10 : includes
    UC_11 ..> UC_10 : extends
    
@enduml