@startuml
actor User
actor Google
database AsyncStorage
boundary LoginScreen
control LoginFilter
control UserService
control HydraRepository
database DB

User -> LoginScreen : signWithGoogle()
activate LoginScreen
LoginScreen -> Google : googleSignIn()

activate Google
Google --> LoginScreen: IDToken
deactivate Google
LoginScreen -> LoginFilter: **POST /auth/login** (IDToken)
activate LoginFilter
LoginFilter -> Google: verifyToken(IDToken)


alt valid ID Token 
activate Google
Google --> LoginFilter : User
deactivate Google
LoginFilter -> UserService : userExists(userId)
activate UserService
UserService -> HydraRepository : userExists(userId)
activate HydraRepository
HydraRepository -> DB 
activate DB
DB --> HydraRepository
deactivate DB
HydraRepository --> UserService
deactivate HydraRepository

alt user exists
UserService --> LoginFilter : true
deactivate UserService

else user does not exist

UserService --> LoginFilter : false
activate UserService

LoginFilter -> UserService : createUser(User)
UserService -> HydraRepository : createUser(User)
activate HydraRepository
HydraRepository -> DB
activate DB
DB --> HydraRepository : ok
deactivate DB
HydraRepository --> UserService : ok
deactivate HydraRepository
UserService --> LoginFilter : ok
deactivate UserService
end

LoginFilter -> LoginFilter: generateJwt(userId)
LoginFilter --> LoginScreen : jwtToken
deactivate LoginFilter
collections AsyncStorage
LoginScreen -> AsyncStorage: saveJwtToken(jwtToken)
activate AsyncStorage
AsyncStorage --> LoginScreen : ok
deactivate AsyncStorage
LoginScreen -> LoginScreen : navigateToWikiScreen()

ref over LoginScreen : **UC_4** 


else invalid ID Token 
activate Google
activate LoginFilter
Google --> LoginFilter : validation failure message
deactivate Google
LoginFilter --> LoginScreen : error message
deactivate LoginFilter
LoginScreen -> LoginScreen : showLoginError()
end

box "Client" #LightBlue
   participant LoginScreen
   participant AsyncStorage
end box

box "External API" #White
   participant Google
end box

box "Server" #Pink
   participant LoginFilter
   participant UserService
   participant HydraRepository
end box

box "Model" #Orange
   participant DB
end box

@enduml