@startuml
actor User
boundary ReferralScreen
control HydraController
control ReferralService
control HydraRepository

database DB

box "Client" #LightBlue
   participant ReferralScreen
end box

box "Server" #Pink
   control HydraController
    control ReferralService
    control HydraRepository
end box

box "Model" #Orange
   participant DB
end box

User -> ReferralScreen : navigateToReferralScreen()
activate ReferralScreen
ref over ReferralScreen : **UC_4 / DECORATE**\n**REQUEST WITH**\n**JWT TOKEN**
ReferralScreen -> HydraController : **GET /referral/referrals** (token)
ref over HydraController : **UC_4 / VALIDATE USER TOKEN**

activate HydraController
HydraController -> ReferralService : getReferrals()
activate ReferralService
ReferralService -> HydraRepository : getReferrals()
activate HydraRepository
HydraRepository -> DB
activate DB
DB --> HydraRepository 
deactivate DB
HydraRepository --> ReferralService : List<ReferralAnnouncement>
deactivate HydraRepository
ReferralService --> HydraController : List<ReferralAnnouncement>
deactivate ReferralService
HydraController --> ReferralScreen : List<ReferralAnnouncement>
deactivate HydraController
ReferralScreen -> ReferralScreen : renderReferrals()


@enduml