@startuml
actor User
boundary JobScreen
control HydraController
control JobService
control HydraRepository

database DB

box "Client" #LightBlue
   participant JobScreen
end box

box "Server" #Pink
   control HydraController
    control JobService
    control HydraRepository
end box

box "Model" #Orange
   participant DB
end box

User -> JobScreen : navigateToJobScreen()
activate JobScreen
ref over JobScreen : **UC_2**
JobScreen -> HydraController : **GET /job/jobs** (token)
ref over HydraController : **UC_3**

activate HydraController
HydraController -> JobService : getJobs()
activate JobService
JobService -> HydraRepository : getJobs()
activate HydraRepository
HydraRepository -> DB
activate DB
DB --> HydraRepository 
deactivate DB
HydraRepository --> JobService : List<JobAnnouncement>
deactivate HydraRepository
JobService --> HydraController : List<JobAnnouncement>
deactivate JobService
HydraController --> JobScreen : List<JobAnnouncement>
deactivate HydraController
JobScreen -> JobScreen : renderJobs()


@enduml