@startuml
left to right direction

actor user

  usecase UC_1 as "**UC_1**
  // Auth // 
  Logowanie za pomocą konta Google"

  usecase UC_4 as "**UC_4** 
  // Wiki // 
  Wyświetl listę wpisów w Wiki"
  usecase UC_5 as "**UC_5** 
  // Wiki // 
  Dodaj wpis do Wiki"
  usecase UC_6 as "**UC_6** 
  // Wiki // 
  Zagłosuj na wpis na Wiki"

    user ---> UC_1
    user ---> UC_4

    UC_5 ..> UC_4 : extends
    UC_6 ..> UC_4 : extends
    UC_1 ..> UC_4 : includes
    
@enduml